module VerifyExamples.UrlExtension.FromString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import UrlExtension exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromString: \n\n    fromString \"ftp://internet.address.edu/path/file.gz\"\n    --> Just { fragment = Nothing, host = \"internet.address.edu\", path = \"/path/file.gz\", port_ = Nothing, protocol = FTP, query = Nothing }" <|
        \() ->
            Expect.equal
                (
                fromString "ftp://internet.address.edu/path/file.gz"
                )
                (
                Just { fragment = Nothing, host = "internet.address.edu", path = "/path/file.gz", port_ = Nothing, protocol = FTP, query = Nothing }
                )