module VerifyExamples.UrlExtension.FromStringWithProtocol0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import UrlExtension exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromStringWithProtocol: \n\n    fromStringWithProtocol [\"ipfs\", \"custom\"] \"custom://RouteTo/http://example.com\"\n    --> Just { fragment = Nothing, host = \"RouteTo\", path = \"/http://example.com\", port_ = Nothing, protocol = CUSTOM \"custom\", query = Nothing }" <|
        \() ->
            Expect.equal
                (
                fromStringWithProtocol ["ipfs", "custom"] "custom://RouteTo/http://example.com"
                )
                (
                Just { fragment = Nothing, host = "RouteTo", path = "/http://example.com", port_ = Nothing, protocol = CUSTOM "custom", query = Nothing }
                )