module VerifyExamples.UrlExtension.FromString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import UrlExtension exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#fromString: \n\n    fromString \"file://C:/home/user/example.png\"\n    --> Just { fragment = Nothing, host = \"C:\", path = \"/home/user/example.png\", port_ = Nothing, protocol = FILE, query = Nothing }" <|
        \() ->
            Expect.equal
                (
                fromString "file://C:/home/user/example.png"
                )
                (
                Just { fragment = Nothing, host = "C:", path = "/home/user/example.png", port_ = Nothing, protocol = FILE, query = Nothing }
                )