module VerifyExamples.UrlExtension.ToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import UrlExtension exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toString: \n\n    { fragment = Nothing\n    , host = \"bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq\"\n    , path = \"/wiki/Vincent_van_Gogh.html\"\n    , port_ = Nothing\n    , protocol = CUSTOM \"ipfs\"\n    , query = Nothing\n    } |> toString\n    --> \"ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html\"" <|
        \() ->
            Expect.equal
                (
                { fragment = Nothing
                , host = "bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq"
                , path = "/wiki/Vincent_van_Gogh.html"
                , port_ = Nothing
                , protocol = CUSTOM "ipfs"
                , query = Nothing
                } |> toString
                )
                (
                "ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html"
                )